### ISSUE TITLE
Adding file input field to settings page

### ISSUE THREAD

**Issue by noelc10** [vanilophp/demo#43] opened 2020-03-12 02:56 UTC
Good day,

As I follow the docs here: [https://vanilo.io/docs/1.1/settings#adding-setting-to-the-uihttps://vanilo.io/docs/1.1/settings#adding-setting-to-the-ui](https://vanilo.io/docs/1.1/settings#adding-setting-to-the-ui), there is no sample on including a different type of form fields in settings UI, only text and select.

I want to include a file input form field below the name text field on application section on the general settings tab on the settings page.

Sample screenshot: http://prntscr.com/rf20rp

Hoping for a fast response.

**Comment by fulopattila122** [comment] 2020-03-12 08:25
What would be the scope of that file?

**Comment by noelc10** [comment] 2020-03-12 08:32
@fulopattila122 what will happen is to dynamically change the app logo via the admin settings page.
Yet I can't figure it out on how to implement it since the docs have lack of information about implementing different field types to include in admin panel settings page.

Any help and assistance is much appreciated.

**Comment by fulopattila122** [comment] 2020-03-12 08:37
Duplicate of #42 
Let's discuss it there

**Closed by fulopattila122** 2020-03-12 08:37 UTC
Labels: question
